# Create a program that will play the “cows and bulls” game with the user. The game works like this:
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number(Digits should not be
# repeated). For every digit that the user guessed correctly in the correct place, they have a “cow”. For
# every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess,
# tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game
# is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at
# the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:
# Welcome to the Cows and Bulls Game!
# Enter a number:
# >>> 1234
# 2 cows, 0 bulls
# >>> 1250
# 1 cow, 1 bull
# ...
# Until the user guesses the number.

import random
number = []
attempts = 0

#generating a new number
def makenumber():
    for i in range(4):
        x=random.randrange(0,9)
        number.append(x)
       
    if len(number) >len(set(number)): #checking if the list contains duplicate value
        number.clear()
        makenumber()
        
def playgame():
    global attempts
    attempts+=1
    cows=0
    bulls=0
    print("WELCOME TO THE COWS AND BULLS GAME")
    print(number)
    choice = input("please enter 4 digit number to guess")
    guess = []
    for i in range(4):
        guess.append(int(choice[i])) #adding user number to list by converting to integer to compare 
    #cow is used to check the position in a list if it matches cow increamented by 1    
    for i in range(4):
        for j in range(4):
            if guess[i] == number[j]:
                cows+=1
                
#this is used to check if all the numbers matches correctly correctly

    for x in range(4):
        #print(x)
        if guess[x] ==number[x]:
            bulls +=1
    print("bulls",bulls)
    print("cows",cows)
    
    if(bulls == 4):
        print("you won after ", attempts,"attempts")
            
    elif bulls!=4:
        if cows==5:
            print("finished")
        elif attempts==10:
            print("finished you have reached your limit")
        else:
            playgame()
            
makenumber()
playgame()
        
        

    
    

        
        


    

